### PR TITLE
Fabricate rewrite

### PR DESCRIPTION
**Pull request by aaronrudkin**
This is the rewrite of fabricate, the level commands, and the vignette. In addition to substantial speed improvements on both nesting and modifying levels, I think the code is much more substantially documented and has better error-proofing.

Some notes:

1. There is unused code in this version, some of which is intended for the cross-classified data in the future -- particularly that the working environment will log variables added and level IDs but that these are not used yet.
2. Code coverage will almost certainly decrease as I have not written unit tests specifically for many of the new error-handling pathways.
3. I think ultimately before CRAN I will move each of the level commands into their own files -- there's also a small bit of redundancy in the different level commands (it's difficult to deduplicate because now each level command has a slightly different approach for handling the data as it writes new variables)
4. There are probably a few places where there's a bunch of nested functions and I think I will go back and adjust the readability -> efficiency tradeoff a little bit.

I'll be taking feedback on code review, including my own, and writing the unit tests to hit as much of the new code as possible. In general I'm viewing this as a sort of "first version", a rewrite more than a refactor.

### CODE REVIEW

**Comment by aaronrudkin** [comment]
Conflicts were all a bunch of line edits to the documentation (graeme had made a doc update pass after I created the feature branch but before I rewrote all the documentation). I am surprised the WYSIWYG editor doesn't let you just press a button to say "trust branch x for all edits" or whatever. *shrugs*

**Comment by aaronrudkin** [comment]
I can live with this coverage decrease. Depending on which tasks take priority today, I can probably have the additional tests and integrated written before the demo.

**Comment by aaronrudkin** [comment]
As per our meeting, we are not merging this until after the demo.

**Comment by graemeblair** [comment]
Small thing: can you use `clusters` rather than `cluster_ids` so we are consistent across packages?

**Comment by aaronrudkin** [comment]
Closing for now, going to finish the unit tests for the rewrite and reissue it.

**Pull request closed without merging**
