### PR TITLE
Nfultz/sac level PR 4/4

### PR DESCRIPTION
**Pull request by nfultz**
Allows tighter scoping with modify_level as in #119 

Needs a better name, deliberating chose a bad one that's easy to find-replace.

```
> fabricate(sleep, sleep=sac_level(by="group", ybar=mean(extra)))
   extra group ID ybar
1    0.7     1  1 0.75
2   -1.6     1  2 0.75
3   -0.2     1  3 0.75
4   -1.2     1  4 0.75
5   -0.1     1  5 0.75
6    3.4     1  6 0.75
7    3.7     1  7 0.75
8    0.8     1  8 0.75
9    0.0     1  9 0.75
10   2.0     1 10 0.75
11   1.9     2  1 2.33
12   0.8     2  2 2.33
13   1.1     2  3 2.33
14   0.1     2  4 2.33
15  -0.1     2  5 2.33
16   4.4     2  6 2.33
17   5.5     2  7 2.33
18   1.6     2  8 2.33
19   4.6     2  9 2.33
20   3.4     2 10 2.33
```

### CODE REVIEW

**Comment by acoppock** [comment]
I think that this accomplishes something very close to what we want.

Here was the original problem:
```
fabricate(
  states = add_level(N = 5),
  schools = add_level(N = 3, test = N)
)
```

produced:
```
  states schools test
1       1      01   15
2       1      02   15
3       1      03   15
4       2      04   15
5       2      05   15
6       2      06   15
7       3      07   15
8       3      08   15
9       3      09   15
10      4      10   15
11      4      11   15
12      4      12   15
13      5      13   15
14      5      14   15
15      5      15   15
```

i.e., N = 15 even though N should be 3.

Now we can write:
```
fabricate(
  states = add_level(N = 5),
  schools = add_level(N = 3),
  schools = sac_level(by = "states", test = N)
)
```

and get

```
   states schools test
1       1      01    3
2       1      02    3
3       1      03    3
4       2      04    3
5       2      05    3
6       2      06    3
7       3      07    3
8       3      08    3
9       3      09    3
10      4      10    3
11      4      11    3
12      4      12    3
13      5      13    3
14      5      14    3
15      5      15    3
```

which is correct.

2 questions:

1. Is there a way to do this in one step. (i.e., I don't have to add a level before s-a-c)
2. How come `add_level` knows about the higher structure, but we have to explicitly tell `sac_level`.

naming brainstorm:

- add_level_by_group
- add_level(sac = TRUE)
- add_level_by

**Comment by nfultz** [comment]
> 2 questions:
> 
> Is there a way to do this in one step. (i.e., I don't have to add a level before s-a-c)

I thought you wanted a variant of modify_level, not add_level.  I think there should be only one way to create a new level though.

> How come add_level knows about the higher structure, but we have to explicitly tell sac_level.

add_level doesn't actually "know" about any structure at all, it just uses the last data frame that was generated. sac_level does the same, you just have to tell it which column to split by - this is confusing because fabricatr always uses the same name for nesting level and for id columns, but they are not the same thing / concept.

**Comment by nfultz** [comment]
> naming brainstorm:
> 
> add_level_by_group
> add_level(sac = TRUE)

Adding flags that make a function do something completely different is an antipattern - see eg https://www.martinfowler.com/bliki/FlagArgument.html

> add_level_by

**Comment by acoppock** [comment]
Thanks for the pointer on flags. 
I had been thinking of this as add_level, but perhaps you're right that it's `modify`.  How would this change if modify had a `by` argument, and we leave it at that?

**Comment by nfultz** [comment]
Could roll it into modify_level, but then modify_level essentially has 3 modes - normal, sac, and the single-run-with-ave mode, all differing in how magic N works. If we got rid of the legacy/single-run mode, normal mode can become a special case of sac mode.

**Comment by acoppock** [comment]
I'm unfamiliar with that last case, the single-run-with-ave mode. What's it for?

**Comment by nfultz** [comment]
It accomplishes the same thing as sac_level with different syntax - see #79 and #119

**Comment by acoppock** [comment]
Ok, well, that's a good argument to remove and have only two cases for modify_level, by = NULL and by = SOMETHING

**Comment by graemeblair** [comment]
Is this single-run-with-AVE-mode?

```
fabricate(
  states = add_level(N = 5),
  schools = add_level(N = 3,
     income = rnorm(N),
     test = ave(income, states)
  )
)
```

If so, just so I understand, what would removing that functionality mean? Just not documenting it?

**Comment by nfultz** [comment]
the legacy mode triggers when the ID column has duplicates - https://github.com/DeclareDesign/fabricatr/blob/master/R/modify_level.R#L75 - which made sense when there was only one data.frame instead of a directed graph of data frames - the syntax for modifying higher levels (vs a split-apply-combine) should get some more thought and clarity.

**Comment by graemeblair** [comment]
agreed re more thinking needed how to modify higher levels

**Pull request closed without merging**
